### PR TITLE
Update workflow yml files to move jdk16 to jdk17

### PR DESCRIPTION
**Pull request by sayali0710**
Update workflow yml files to move jdk16 to jdk17

### CODE REVIEW

**Review by sophia-guo — APPROVED** [review]
LGTM

**Comment by sophia-guo** [comment]
@sayali0710 Don't forget to sign the ECA with the same email as your GitHub account.
https://www.eclipse.org/legal/ECA.php

**Comment by sayali0710** [comment]
@sophia-guo - I just signed it how do I rerun

**Comment by smlambert** [comment]
can you try pushing another change to the PR?  sayali_gole@****.com is the address its trying to validate, is that correct one (associated with the commit)?

**Pull request closed without merging**
